---
# BWC PackageCloud repository to install: enterprise, enterprise-unstable, staging-enterprise, staging-enterprise-unstable.
bwc_repo: "enterprise"
# `present` to install available package, `latest` to get automatic updates, or pin it to numeric version like `2.2.0`.
bwc_version: latest
# used only if 'bwc_version' is numeric
bwc_revision: 1

# BWC license to install BWC enterprise bits
bwc_license: null

# Specify roles, assignments, and group mappings for BWC RBAC.
# Roles are pushed as YML files to /opt/stackstorm/rbac/roles
# Assignments are pushed as YML files to /opt/stackstorm/rbac/assignments/
# Mappings are pushed as YML files to /opt/stackstorm/rbac/mappings/
# The schema for roles, assignments, and mappings follow the exact schema definition
# define in https://bwc-docs.brocade.com/rbac.html#defining-roles-and-permission-grants
# and https://bwc-docs.brocade.com/rbac.html#defining-user-role-assignments
# and https://bwc-docs.brocade.com/rbac.html#automatically-granting-roles-based-on-the-user-ldap-group-membership.

bwc_rbac_default_roles: []

bwc_rbac_default_assignments:
  - name: "{{ st2_system_user }}"
    roles:
      - admin

  - name: "{{ st2_auth_username }}"
    roles:
      - system_admin

bwc_rbac_default_mappings: []

bwc_rbac:
  roles: "{{ bwc_rbac_default_roles }}"

  assignments: "{{ bwc_rbac_default_assignments }}"

  mappings: "{{ bwc_rbac_default_mappings }}"


# By specifying a valid configuration for LDAP,
# (See https://bwc-docs.brocade.com/authentication.html#ldap )
# LDAP auth backend is setup for st2 and BWC.
# Note that you just need to provide the backend_kwargs.
bwc_ldap:
  backend_kwargs: {}
